(require :asdf)
(asdf:load-system :starintel-legacy)
(assert (find-package :starintel.legacy))
(assert (eq (find-package :starintel.legacy) (find-package :spec.legacy)))
(assert (null (find-package :spec)))
(assert (equal starintel.legacy:+starintel-doc-version+ "0.9.0"))
(assert (null (find-package :starintel.canonical)))
(let* ((person (starintel.legacy:create 'starintel.legacy:person :dataset "test" :fname "Ada"))
       (wire (starintel.legacy:encode-document-v09 person)))
  (assert (equal (jsown:val wire "schema_version") "0.9.0"))
  (assert (jsown:val wire "_id"))
  (assert (jsown:val wire "data")))
;; Loading canonical after explicit legacy does not inherit historical exports.
(asdf:load-system :starintel)
(assert (equal starintel:+starintel-doc-version+ "0.10.1"))
(assert (equal starintel.legacy:+starintel-doc-version+ "0.9.0"))
(dolist (dtype (starintel:document-types))
  (assert (null (find-class (find-symbol (string-upcase dtype) :starintel) nil))))
(format t "Fresh explicit legacy opt-in and canonical namespace isolation passed.~%")
