(require :asdf)
(asdf:load-system :starintel)
(assert (null (find-package :starintel.legacy)))
(assert (null (find-package :spec)))
(assert (null (find-package :spec.legacy)))
(let* ((person (starintel:person :id "person:root" :dataset "test" :fname "Ada" :deleted :false))
       (json (starintel:to-json person))
       (roundtrip (starintel:encode-document (starintel:from-json json))))
  (assert (equal (gethash "schemaVersion" roundtrip) "0.10.1"))
  (assert (equal (starintel:doc-id person) "person:root"))
  (assert (not (nth-value 1 (gethash "_id" roundtrip))))
  (assert (not (nth-value 1 (gethash "data" roundtrip)))))
(format t "Fresh canonical root API passed; no legacy packages loaded.~%")
