(require :asdf)
(asdf:load-system :starintel)
(assert (null (find-package :starintel.legacy)))
(assert (null (find-package :spec)))
(assert (equal starintel:+starintel-doc-version+ "0.10.1"))
(assert (equal starintel:+starintel-schema-version+ "0.10.1"))
(assert (equal starintel:+starintel-release-version+ "0.10.1"))
(assert (not (eq (nth-value 1 (find-symbol "+STARINTEL-V090-SCHEMA-VERSION+" :starintel)) :external)))
(let* ((documents (com.inuoe.jzon:parse *standard-input*))
       (results (make-array (length documents))))
  (loop for doc across documents for i from 0
        for dtype = (gethash "dtype" doc)
        for symbol = (find-symbol (string-upcase dtype) :starintel)
        for fields = (loop for key being the hash-keys of doc using (hash-value value)
                           unless (member key '("dtype" "schemaVersion") :test #'equal)
                           append (list (intern (string-upcase key) :keyword) value))
        do (assert (eq (nth-value 1 (find-symbol (string-upcase dtype) :starintel)) :external))
           (let* ((created (apply (symbol-function symbol) fields))
                  (decoded (starintel:from-json (starintel:to-json created))))
             (setf (aref results i) (starintel:encode-document decoded))))
  (write-line (com.inuoe.jzon:stringify results)))
