(in-package :starintel)

;; Jzon's public reader always converts fractional/exponent tokens to binary
;; doubles, and its extensible writer exposes no public raw-number operation.
;; Own the JSON boundary rather than patching its internals or recovering tokens
;; after a lossy parse. Delegate only JSON strings and ordinary scalar writing.
(defstruct (json-number (:constructor %make-json-number (lexeme)))
  "An exact JSON fractional/exponent token, independent of binary float range."
  (lexeme "0.0" :type string :read-only t))

(defun json-number-token-p (token)
  (multiple-value-bind (start end)
      (cl-ppcre:scan "^-?(?:0|[1-9][0-9]*)(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?$" token)
    (and start (zerop start) (= end (length token)))))

(defun parse-json (input)
  "Parse strict JSON from a string, character stream, or UTF-8 pathname.
Integers are native arbitrary-precision integers. Fractional/exponent tokens
are JSON-NUMBER values: their lexemes survive STRINGIFY-JSON exactly. Arrays
are vectors, objects are hash tables, false is NIL, and null is CL:NULL."
  (let* ((source (etypecase input
                   (string input)
                   (pathname (uiop:read-file-string input :external-format :utf-8))
                   (stream (uiop:slurp-stream-string input))))
         (position 0)
         (length (length source)))
    (labels ((fail (message)
               (error 'com.inuoe.jzon:json-parse-error
                      :format-control "~a at character ~d"
                      :format-arguments (list message position)
                      :line nil :column nil))
             (peek () (when (< position length) (char source position)))
             (space-p (char) (and char (find char '(#\Space #\Tab #\Return #\Newline))))
             (skip-space () (loop while (space-p (peek)) do (incf position)))
             (take (char)
               (when (eql (peek) char) (incf position) t))
             (expect (char) (unless (take char) (fail (format nil "Expected ~s" char))))
             (string-value ()
               (let ((start position))
                 (expect #\")
                 (loop
                   (unless (peek) (fail "Unterminated JSON string"))
                   (let ((char (char source position)))
                     (incf position)
                     (cond
                       ((char= char #\\)
                        (unless (peek) (fail "Unterminated JSON escape"))
                        (incf position))
                       ((char= char #\")
                        (return (com.inuoe.jzon:parse (subseq source start position)))))))))
             (literal (token value)
               (let ((end (+ position (length token))))
                 (unless (and (<= end length) (string= token source :start2 position :end2 end))
                   (fail "Invalid JSON literal"))
                 (setf position end)
                 value))
             (number-value ()
               (let* ((start position)
                      (end (or (position-if (lambda (char)
                                              (or (space-p char) (find char ",]}")))
                                            source :start start)
                               length))
                      (token (subseq source start end)))
                 (unless (json-number-token-p token) (fail "Invalid JSON number"))
                 (setf position end)
                 (if (find-if (lambda (char) (find char ".eE")) token)
                     (%make-json-number token)
                     (parse-integer token))))
             (value (depth)
               (skip-space)
               (unless (peek) (fail "Expected JSON value"))
               (case (peek)
                 (#\" (string-value))
                 (#\t (literal "true" t))
                 (#\f (literal "false" nil))
                 (#\n (literal "null" 'null))
                 (#\{
                  (when (>= depth 128) (fail "JSON exceeds maximum depth 128"))
                  (incf position)
                  (skip-space)
                  (let ((object (make-hash-table :test 'equal)))
                    (unless (take #\})
                      (loop
                        (unless (eql (peek) #\") (fail "Expected JSON object key"))
                        (let ((key (string-value)))
                          (skip-space) (expect #\:)
                          (setf (gethash key object) (value (1+ depth))))
                        (skip-space)
                        (when (take #\}) (return))
                        (expect #\,) (skip-space)))
                    object))
                 (#\[
                  (when (>= depth 128) (fail "JSON exceeds maximum depth 128"))
                  (incf position)
                  (skip-space)
                  (let ((items nil))
                    (unless (take #\])
                      (loop
                        (push (value (1+ depth)) items)
                        (skip-space)
                        (when (take #\]) (return))
                        (expect #\,) (skip-space)))
                    (coerce (nreverse items) 'vector)))
                 (otherwise (number-value)))))
      (let ((result (value 0)))
        (skip-space)
        (unless (= position length) (fail "Unexpected content after JSON value"))
        result))))

(defun json-finite-float-p (value)
  (handler-case (progn (rational value) t) (error () nil)))

(defun stringify-json (value)
  "Encode JSON data without rounding JSON-NUMBER values or bignum integers."
  (with-output-to-string (out)
    (labels ((emit (item ancestors)
               (when (member item ancestors :test #'eq)
                 (error 'com.inuoe.jzon:json-write-error :format-control "Recursive JSON data"))
               (when (and (or (hash-table-p item) (consp item)
                              (and (vectorp item) (not (stringp item))))
                          (>= (length ancestors) 128))
                 (error 'com.inuoe.jzon:json-write-error :format-control "JSON exceeds maximum depth 128"))
               (typecase item
                 (json-number
                  (unless (json-number-token-p (json-number-lexeme item))
                    (error 'com.inuoe.jzon:json-write-error :format-control "Invalid JSON number token"))
                  (write-string (json-number-lexeme item) out))
                 (float
                  (unless (json-finite-float-p item)
                    (error 'com.inuoe.jzon:json-write-error :format-control "Non-finite floats are not JSON numbers"))
                  (write-string (com.inuoe.jzon:stringify item) out))
                 ((or string integer (eql t) (eql nil) (eql null))
                  (write-string (com.inuoe.jzon:stringify item) out))
                 (hash-table
                  (write-char #\{ out)
                  (let ((first t))
                    (maphash (lambda (key child)
                               (unless (stringp key)
                                 (error 'com.inuoe.jzon:json-write-error :format-control "JSON object keys must be strings"))
                               (unless first (write-char #\, out))
                               (setf first nil)
                               (write-string (com.inuoe.jzon:stringify key) out)
                               (write-char #\: out)
                               (emit child (cons item ancestors))) item))
                  (write-char #\} out))
                 ((or vector cons)
                  (when (consp item)
                    (unless (handler-case (list-length item) (type-error () nil))
                      (error 'com.inuoe.jzon:json-write-error :format-control "JSON arrays require finite proper lists")))
                  (write-char #\[ out)
                  (let ((first t))
                    (map nil (lambda (child)
                               (unless first (write-char #\, out))
                               (setf first nil)
                               (emit child (cons item ancestors))) item))
                  (write-char #\] out))
                 (t (error 'com.inuoe.jzon:json-write-error
                           :format-control "Not JSON data: ~s" :format-arguments (list item))))))
      (emit value nil))))

(defun json-numeric-p (value)
  (or (numberp value) (json-number-p value)))

(defun json-decimal-parts (value)
  "Return sign, significant digits and decimal order, without expanding powers."
  (let* ((token (if (json-number-p value) (json-number-lexeme value)
                    (com.inuoe.jzon:stringify value)))
         (negative (char= (char token 0) #\-))
         (start (if negative 1 0))
         (e (or (position-if (lambda (char) (find char "eE")) token) (length token)))
         (point (or (position #\. token :end e) e))
         (digits (remove #\. (subseq token start e)))
         (leading (position-if-not (lambda (char) (char= char #\0)) digits))
         (exponent (if (< e (length token)) (parse-integer token :start (1+ e)) 0)))
    (if (null leading)
        (values 0 "0" 0)
        (values (if negative -1 1) (subseq digits leading)
                (+ exponent (- point start leading))))))

(defun json-numeric-less-p (left right)
  "Compare exact JSON numbers without binary rounding or exponent expansion."
  (if (and (numberp left) (numberp right))
      (< left right)
      (multiple-value-bind (ls ld lo) (json-decimal-parts left)
        (multiple-value-bind (rs rd ro) (json-decimal-parts right)
          (cond
            ((/= ls rs) (< ls rs))
            ((zerop ls) nil)
            ((/= lo ro) (if (plusp ls) (< lo ro) (> lo ro)))
            (t (loop for index below (max (length ld) (length rd))
                     for lc = (if (< index (length ld)) (char ld index) #\0)
                     for rc = (if (< index (length rd)) (char rd index) #\0)
                     when (char/= lc rc)
                       return (if (plusp ls) (char< lc rc) (char> lc rc))
                     finally (return nil))))))))

(export '(parse-json stringify-json json-number json-number-p json-number-lexeme))

(defun json-integer-p (value)
  "JSON Schema integers are numbers with no fractional part, including 1e0."
  (cond
    ((integerp value) t)
    ((json-number-p value)
     (multiple-value-bind (sign digits order) (json-decimal-parts value)
       (or (zerop sign)
           (>= order (length (string-right-trim "0" digits))))))
    ((floatp value) (and (json-finite-float-p value) (zerop (nth-value 1 (truncate value)))))
    (t nil)))
