(in-package :starintel)

(export '(+starintel-doc-version+
          +schema-org-context+
          +canonical-dtypes+
          *dtype-aliases*
          *dtype-schema-org-types*
          canonical-dtype
          schema-org-types
          schema-org-metadata
          utc-now
          document-envelope-slot-p
          doc-rev
          doc-schema-version
          doc-version
          doc-title
          doc-summary
          doc-description
          doc-status
          doc-language
          doc-tags
          doc-labels
          doc-aliases
          doc-keywords
          doc-identifiers
          doc-evidence
          doc-temporal
          doc-provenance
          doc-assessment
          doc-verification
          doc-handling
          doc-lineage
          doc-quality
          doc-workflow
          doc-geospatial
          doc-attachments
          doc-related-ids
          doc-notes
          doc-schema-org
          doc-data
          doc-extensions
          refresh-schema-org
          touch
          update-timestamp
          define-docs
          read-star-file
          codec-validation-error
          codec-validation-operation
          codec-validation-path
          codec-validation-expected-type
          codec-validation-value
          codec-validation-reason
          unknown-document-dtype
          document-class-mismatch
          encode-value
          decode-value
          encode-document-v09
          decode-document-v09
          decode-document
          register-document-class
          registered-document-class
          registered-document-dtypes
          digest-id
          relation-subject
          relation-object)
        (find-package :starintel))
