(in-package :starintel.canonical)

(defun validate-operation-semantics (document)
  "Enforce the research operation invariants declared by the pinned core.star."
  (unless (equal (gethash "dtype" document) "operation")
    (return-from validate-operation-semantics document))
  (labels ((reject (message)
             (starintel::reject-document "operation_semantics" "~a" message))
           (items (object key) (coerce (gethash key object) 'list))
           (nonempty (value)
             (and (stringp value) (plusp (length (string-trim '(#\Space #\Tab #\Newline #\Return) value)))))
           (ids (values key)
             (let ((known (make-hash-table :test 'equal)))
               (dolist (value values known)
                 (let ((id (gethash key value)))
                   (unless (nonempty id) (reject "Empty component identifier"))
                   (setf id (string-trim '(#\Space #\Tab #\Newline #\Return) id))
                   (when (gethash id known) (reject "Duplicate component identifier"))
                   (setf (gethash id known) t)))))
           (references (values known)
             (dolist (value values)
               (unless (gethash value known) (reject "Unknown local operation reference")))))
    (let* ((phases (items document "phases"))
           (datasets (items document "datasets"))
           (capabilities (items document "capabilityGaps"))
           (assignments (items document "assignments"))
           (actions (items document "postActions"))
           (phase-ids (ids phases "phaseId"))
           (dataset-ids (ids datasets "bindingId"))
           (capability-ids (ids capabilities "capabilityId"))
           (graph (make-hash-table :test 'equal))
           (visiting (make-hash-table :test 'equal))
           (visited (make-hash-table :test 'equal)))
      (unless (nonempty (gethash "mission" document)) (reject "Nonempty mission required"))
      (unless phases (reject "At least one phase required"))
      (ids assignments "assignmentId")
      (ids actions "actionId")
      (dolist (phase phases)
        (let ((id (string-trim '(#\Space #\Tab #\Newline #\Return) (gethash "phaseId" phase)))
              (dependencies (items phase "dependsOn")))
          (references dependencies phase-ids)
          (setf (gethash id graph) dependencies))
        (unless (nonempty (gethash "objective" phase)) (reject "Nonempty phase objective required"))
        (references (items phase "datasetBindingIds") dataset-ids)
        (references (items phase "requiredCapabilityIds") capability-ids)
        (when (intersection (items document "outOfScope") (items phase "inScope") :test #'equal)
          (reject "Phase scope contradicts operation exclusions"))
        (when (and (equal (gethash "state" phase) "completed")
                   (null (items phase "completionEvidence")))
          (reject "Completed phase requires evidence"))
        (when (and (equal (gethash "status" document) "completed")
                   (not (member (gethash "state" phase) '("completed" "skipped") :test #'equal)))
          (reject "Completed operation contains nonterminal phase")))
      (labels ((visit (id)
                 (when (gethash id visiting) (reject "Phase dependency cycle"))
                 (unless (gethash id visited)
                   (setf (gethash id visiting) t)
                   (dolist (dependency (gethash id graph)) (visit dependency))
                   (remhash id visiting)
                   (setf (gethash id visited) t))))
        (maphash (lambda (id ignored) (declare (ignore ignored)) (visit id)) phase-ids))
      (dolist (binding datasets) (references (items binding "phases") phase-ids))
      (dolist (capability capabilities) (references (items capability "requiredBy") phase-ids))
      (dolist (assignment assignments) (references (items assignment "phaseIds") phase-ids))
      (dolist (action actions) (references (items action "datasetBindingIds") dataset-ids))))
  document)


(defun validate-workflow-semantics (document)
  "Enforce the injective typed-map mapping declared by core.star."
  (when (equal (gethash "dtype" document) "dataset-manifest")
    (let ((seen (make-hash-table :test 'equal)))
      (loop for entry across (or (gethash "countsByDtype" document) #())
            for key = (gethash "key" entry)
            do (when (gethash key seen)
                 (starintel::reject-document "workflow_semantics" "Duplicate countsByDtype key ~a" key))
               (setf (gethash key seen) t))))
  document)
