(in-package :starintel)

(defparameter +schema-org-context+ "https://schema.org/")

(defparameter +canonical-dtypes+
  '("actor-manifest" "address" "alert" "analysis" "asset" "breach"
    "campaign-finance" "claim" "concept" "contract" "dataset-manifest"
    "document" "domain" "education" "email" "email-message" "employment"
    "entity" "event" "evidence-record" "file" "financial-observation" "geo"
    "grant" "host" "investigation-target" "legal-case" "lobbying-filing"
    "location" "media" "meeting" "message" "network" "observation" "org"
    "ownership" "person" "phone" "policy" "procurement" "product" "relation"
    "research-pass" "social-media-post" "source" "target" "task" "url" "user"))

(defparameter *dtype-aliases*
  '(("organization" . "org")
    ("organisation" . "org")
    ("geolocation" . "geo")
    ("geographic-location" . "geo")
    ("email-address" . "email")
    ("electronic-mail" . "email")
    ("emailmessage" . "email-message")
    ("hostname" . "host")
    ("phone-number" . "phone")
    ("telephone" . "phone")
    ("telephone-number" . "phone")
    ("uniform-resource-locator" . "url")
    ("web-url" . "url")
    ("socialmpost" . "social-media-post")
    ("socialmediapost" . "social-media-post")
    ("investigationtarget" . "investigation-target")
    ("researchpass" . "research-pass")
    ("datasetmanifest" . "dataset-manifest")
    ("actormanifest" . "actor-manifest")
    ("legalcase" . "legal-case")
    ("lobbyingfiling" . "lobbying-filing")
    ("campaignfinance" . "campaign-finance")
    ("financialobservation" . "financial-observation")
    ("evidencerecord" . "evidence-record")))

(defparameter *dtype-schema-org-types*
  '(("actor-manifest" . ("CreativeWork"))
    ("address" . ("PostalAddress"))
    ("alert" . ("SpecialAnnouncement"))
    ("analysis" . ("CreativeWork"))
    ("asset" . ("Thing"))
    ("breach" . ("Event"))
    ("campaign-finance" . ("CreativeWork"))
    ("claim" . ("Claim"))
    ("concept" . ("DefinedTerm"))
    ("contract" . ("DigitalDocument"))
    ("dataset-manifest" . ("Dataset"))
    ("document" . ("CreativeWork"))
    ("domain" . ("WebSite"))
    ("education" . ("EducationalOccupationalCredential"))
    ("email" . ("ContactPoint"))
    ("email-message" . ("Message"))
    ("employment" . ("OrganizationRole"))
    ("entity" . ("Thing"))
    ("event" . ("Event"))
    ("evidence-record" . ("CreativeWork"))
    ("file" . ("DigitalDocument"))
    ("financial-observation" . ("CreativeWork"))
    ("geo" . ("GeoCoordinates"))
    ("grant" . ("Grant"))
    ("host" . ("Thing"))
    ("investigation-target" . ("Thing"))
    ("legal-case" . ("CreativeWork"))
    ("lobbying-filing" . ("DigitalDocument"))
    ("location" . ("Place"))
    ("media" . ("MediaObject"))
    ("meeting" . ("Event"))
    ("message" . ("Message"))
    ("network" . ("Thing"))
    ("observation" . ("CreativeWork"))
    ("org" . ("Organization"))
    ("ownership" . ("Role"))
    ("person" . ("Person"))
    ("phone" . ("ContactPoint"))
    ("policy" . ("CreativeWork"))
    ("procurement" . ("DigitalDocument"))
    ("product" . ("Product"))
    ("relation" . ("Role"))
    ("research-pass" . ("CreativeWork"))
    ("social-media-post" . ("SocialMediaPosting"))
    ("source" . ("CreativeWork"))
    ("target" . ("Thing"))
    ("task" . ("Action"))
    ("url" . ("WebPage"))
    ("user" . ("Person"))))

(defun normalize-dtype-key (value)
  (let ((text (string-downcase (string value))))
    (substitute #\- #\_ (substitute #\- #\Space text))))

(defun canonical-dtype (value)
  (let* ((key (normalize-dtype-key (or value "document")))
         (alias (cdr (assoc key *dtype-aliases* :test #'string=))))
    (cond
      (alias alias)
      ((member key +canonical-dtypes+ :test #'string=) key)
      (t key))))

(defun schema-org-types (dtype)
  (or (cdr (assoc (canonical-dtype dtype) *dtype-schema-org-types* :test #'string=))
      '("Thing")))

(defun schema-org-object-has-key-p (object key)
  (handler-case
      (progn (jsown:val object key) t)
    (error () nil)))

(defun schema-org-metadata (dtype &optional document-id existing)
  (let* ((canonical (canonical-dtype dtype))
         (types (schema-org-types canonical))
         (object (or existing (jsown:empty-object))))
    (unless (schema-org-object-has-key-p object "@context")
      (setf (jsown:val object "@context") +schema-org-context+))
    (unless (schema-org-object-has-key-p object "@type")
      (setf (jsown:val object "@type")
            (if (= (length types) 1) (first types) types)))
    (unless (schema-org-object-has-key-p object "additionalType")
      (setf (jsown:val object "additionalType")
            (format nil "https://starintel.dev/dtype/~a" canonical)))
    (when (and document-id (> (length document-id) 0))
      (setf (jsown:val object "@id") document-id))
    object))

(eval-when (:load-toplevel :execute)
  (let ((mapped (mapcar #'car *dtype-schema-org-types*)))
    (unless (and (= (length mapped) (length +canonical-dtypes+))
                 (every (lambda (dtype) (member dtype mapped :test #'string=))
                        +canonical-dtypes+))
      (error "Schema.org dtype map does not cover the canonical v0.9 dtype set"))))
