(in-package :starintel)

(defclass message (document)
  ((message :accessor message-message :type string :initarg :message :initform "")
   (platform :accessor message-platform :type string :initarg :platform :initform "")
   (user :accessor message-user :type string :initarg :user :initform "")
   (is-reply :accessor message-is-reply :type bool :initarg :is-reply :initform nil)
   (media :accessor message-media :type list :initarg :media :initform '())
   (message-id :accessor message-message-id :type string :initarg :message-id :initform "")
   (reply-to :accessor message-reply-to :type string :initarg :reply-to :initform "")
   (group :accessor message-group :type string :initarg :group :initform "")
   (channel :accessor message-channel :type string :initarg :channel :initform "")
   (mentions :accessor message-mentions :type list :initarg :mentions :initform '())))

(defclass social-media-post (document)
  ((content :accessor social-media-post-content :type string :initarg :content :initform "")
   (user :accessor social-media-post-user :type string :initarg :user :initform "")
   (replies :accessor social-media-post-replies :type list :initarg :replies :initform '())
   (media :accessor social-media-post-media :type list :initarg :media :initform '())
   (reply-count :accessor social-media-post-reply-count :type int :initarg :reply-count :initform 0)
   (repost-count :accessor social-media-post-repost-count :type int :initarg :repost-count :initform 0)
   (url :accessor social-media-post-url :type string :initarg :url :initform "")
   (links :accessor social-media-post-links :type list :initarg :links :initform '())
   (tags :accessor social-media-post-tags :type list :initarg :tags :initform '())
   (title :accessor social-media-post-title :type string :initarg :title :initform "")
   (group :accessor social-media-post-group :type string :initarg :group :initform "")
   (reply-to :accessor social-media-post-reply-to :type string :initarg :reply-to :initform "")))

(defun new-message (message group platform user &optional channel message-id)
  "Create a New Booker Message"
  (let ((message (make-instance 'message :message message :platform platform :user user :is-reply nil :media '() :message-id (or message-id "") :reply-to "" :group group :channel (or channel "") :mentions '())))
    (hash-id message (format nil "~a~a~a~a" message group platform user))
    message))

(defun new-social-media-post (user content title group &optional url date)
  "Create a New Booker Social Media Post"
  (let ((post (make-instance 'social-media-post :content content :user user :replies '() :media '() :reply-count 0 :repost-count 0 :url (or url "") :links '() :tags '() :title title :group group :reply-to "")))
    (hash-id post (format nil "~a~a~a~a" user content title group))
    post))
